### ISSUE TITLE
В проекте мало информации 

### ISSUE THREAD

**Issue by LazarenkoA** [lead-tools/radar#40]
Напишите подробнее в readme какие проверки (что именно проверяется), в чем преимущество перед апк или сонаром

**Comment by tsukanov-as** [comment]
Воу, сюда еще кто-то заходит! :)
Пардон, только увидел сообщения.
Все реализованные на текущий момент (на коленке) проверки тут: https://github.com/lead-tools/radar/tree/dev/plugins
Код там довольно тупой, так что по большей части можно понять что проверяется прямо по коду. В принципе достаточно посмотреть на вызовы типа ```Ошибка("Выполнение запроса в цикле", ...);```
У меня пока нет времени заниматься этим. Возможно позже попилю, напишу ридми, но не факт. Так получилось, что я больше не пересекаюсь с экосистемой 1С.
На вопросы могу ответить в телеге в личке. Лучше там мне писать, так как на гитхабе у меня пинг не всегда проходит.
